default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: rails_crud_camera_app_development

test:
  <<: *default
  database: rails_crud_camera_app_test

production:
  <<: *default
  database: rails_crud_camera_app_production
  username: rails_crud_camera_app
  password: <%= ENV['RAILS_CRUD_CAMERA_APP_DATABASE_PASSWORD'] %>
